### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lightarrow47** [woodruffw/yossarian-bot#13]
Google Maps just got an API, maybe you could put that in and have some sort of Map command, like !map 32901 or !map 4053 Wilkes Drive Melbourne FL 32901 and then it would spit out a link to the address. It could also do Lat/Long coordinates

Also pizza command like taco but for pizza. i cant find a website that isnt from the major pizza makers. perhaps put it out to the community to see if they could find it

**Comment by woodruffw** [comment]
Could you link me to the Google Maps API?

**Comment by lightarrow47** [comment]
https://developers.google.com/maps/?hl=en

**Comment by woodruffw** [comment]
Going to close this issue now that it's in the TODO.
