### ISSUE TITLE
Misleading license at best

### ISSUE THREAD

**Issue by pombredanne** [woodruffw/yossarian-bot#158]
The readme states that this code is MIT-licensed: "licensed under the MIT License." but the license has additional restrictions that means this is not longer the MIT proper and not an open source nor a free software license. It would be nice to clarify to avoid confusion, uncertainty and doubts. NB: this also applies to several other repositories.= of yours

**Comment by woodruffw** [comment]
Thanks for pointing that out. I've tried to update all the metadata associated with my projects' licenses, but sometimes I miss a spot.

If you find other instances where the restricted license is used but is incorrectly labeled, please open separate issues on those repositories.

**Comment by pombredanne** [comment]
Thank you for acting on this so quickly!
