### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by lightarrow47** [woodruffw/yossarian-bot#2]
So you said the youtube app said that some apis will not be supported after april 2015 
![problem](https://cloud.githubusercontent.com/assets/9113444/7238505/e9cbc118-e770-11e4-83cf-7ca7d3d9c465.PNG)

also its not reporting youtube info, must be related to the above item

**Comment by woodruffw** [comment]
YouTube now works again, as of 137d319265cbb025370c419f90035b5421ed0c62.
