### ISSUE TITLE
LastSeen Persistence

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/yossarian-bot#34]
The `LastSeen` plugin does not persist its records across reboots (all seen records are stored in a single hash). This should be changed so that users can look up seen times for people who have not been since since before a reboot.

Ideas:
Look at `UserIntros` or any other persistent plugin for inspiration.

**Comment by bheru27** [comment]
what if, we save the user list on a json file and then load the thing again, also, is the plugin constantly listening or just saves the user list when it connects? because that should be added too, every X hour the user list is updated with new times....

**Comment by woodruffw** [comment]
YAML is preferred, simply because it's what the other persistent plugins use. My model for the other persistent plugins was to load the data from the YAML file on plugin load, then periodically save it to ensure a somewhat updated copy on disk.
