### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/yossarian-bot#35]
IRC isn't case sensitive for nicknames, but some plugins that use nicks probably are.

**Comment by greenbagels** [comment]
@woodruffw for clarification, you want to comb through the plugins and desensitize the nickname parsing, but not the command/argument parsing, correct?

**Comment by woodruffw** [comment]
Yep. `!foo` and `!FOO` should *not* be the same command, but `!foo nick` and `!foo NICK` should have the same effect.
