### ISSUE TITLE
HAL Per-channel and Persistence

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/yossarian-bot#38]
`HAL` does not store its "brain" across reboots. This should be done to maximize learning. Additionally, it should learn on a per-channel basis.

**Comment by winny-** [comment]
According to the megahal docs:

> Train MegaHAL with the contents of the specified file, which should be plain text with one sentence per line. Note that it takes MegaHAL about one second to process about 500 lines, so large files may cause the process to block for a while. Lines that are too long will be skipped.

So I think we might do well to have a megahal instance per channel, as to prevent calling `become` which apparently retrains megahal with a stored personality.

Thoughts? Only concern is it may be memory hungry.

**Comment by woodruffw** [comment]
> So I think we might do well to have a megahal instance per channel, as to prevent calling become which apparently retrains megahal with a stored personality.

Yes, I think that would be good.



> Thoughts? Only concern is it may be memory hungry.

And yeah, that's the problem I've had. I'm open to finding another HAL implementation without the problem, or potentially another chatterbot system.

**Comment by winny-** [comment]
Do we have any numbers, either anecdotal or hard, of the memory usage of HAL instances?

**Comment by woodruffw** [comment]
Anecdotally, HAL running on one server across 6-7 channels triggered the OOM killer on my DO instance (512MB) after a few days.

**Comment by woodruffw** [comment]
Closing because HAL has been moved to the old plugin list.
