### ISSUE TITLE
Ping Accuracy

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/yossarian-bot#41]
Current, `Ping` just acknowledges the user with a UNIX timestamp. This isn't at all accurate, and doesn't give the user a good idea of their latency.

Ideas:
User should send a ISO 8601 stamp via `!ping <stamp>`, which is then subtracted from the current time. The stamp should either be in UTC or include a timezone offset.

**Comment by greenbagels** [comment]
Would the idea really be feasible? I'm not sure if requiring the user to fetch a timestamp manually would be an accurate way to record the send time.

I don't think we should even worry about accuracy --- there's too much abstraction (internal servers and network nodes) between the user, the IRC network, and the bot for there to be a dependable solution (at least, as far as I can tell).

**Comment by woodruffw** [comment]
Yup. This idea is basically DOA.
