### ISSUE TITLE
RuboCop Style Compliance

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/yossarian-bot#53]
The bot should pass a RuboCop lint perfectly.

The style rules are [here](https://github.com/woodruffw/dotfiles/blob/master/rubocop.yml).

**Comment by ericboehs** [comment]
With those style rules, the repository has 1379 offenses. It looks like this is a bit of an undertaking.

**Comment by woodruffw** [comment]
> With those style rules, the repository has 1379 offenses. It looks like this is a bit of an undertaking.

Yep, definitely is.

RuboCop provides an `-a`, `--auto-correct` flag that might be able to fix some of those automatically, but I don't expect any one person to go through the code and do all of them. I've been fixing them on a plugin-by-plugin basis, and I'd happy accept PRs that do the same 😄

**Comment by ericboehs** [comment]
I'll start on this.
