### ISSUE TITLE
Support for environment variables in config

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/yossarian-bot#64]
Various `yossarian-bot` plugins access the evironment for API keys.

It would be good to load such keys from a central location, rather than expecting them to be preloaded into the environment. For example, something like this in `config.yml`:

```yaml
environment:
  FOO_API: value
```

The `environment` hash could then be loaded in `yossarian-bot.rb`.

**Comment by chrisatanasian** [comment]
I'll take this one.
