### ISSUE TITLE
Issue command

### ISSUE THREAD

**Issue by arathnim** [woodruffw/yossarian-bot#69]
A command that uses the github API to submit an issue to this repo, allowing more direct feedback for potential bugfixes.

**Comment by woodruffw** [comment]
I've considered this in the past. There are a few problems:

* The potential for abuse is pretty high (spam issues, API rate exhaustion, etc). 
* I'd probably have to create a separate GitHub bot account
* IRC messages don't map well to issues (Markdown pretty much requires newlines, and IRC doesn't have them)

If you (or anybody else) finds a way around these problems, let me know.

**Comment by greenbagels** [comment]
I think an `!issue` command that posts info about making a github issue would be the best compromise, as it provides a suitable amount of convenience while avoiding the problems pointed out by Will.

**Comment by woodruffw** [comment]
> I think an !issue command that posts info about making a github issue

Yes, that would be good.

**Comment by woodruffw** [comment]
Closing in favor of using `CustomTriggers` to define an `!issue` trigger.
