### ISSUE TITLE
A new Weather plugin

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/yossarian-bot#74]
As of https://github.com/woodruffw/yossarian-bot/commit/90fe0e4f5583e377318516d1a6776167ad9dead1, the old (Wunderground-based) `Weather` plugin has been disabled -- Wunderground appears to have broken much of the search functionality in their API.

Open to suggestions and PRs for a new `Weather` plugin.

**Comment by winny-** [comment]
List of some public weather APIs - https://github.com/toddmotto/public-apis#weather

Metaweather looks promising because it requires no apikey and does not have an apparent rate limit. It has been around since 2017, so it is might be stable enough to use. https://www.metaweather.com/api/

**Comment by winny-** [comment]
Scratch Metaweather - searching by location "53211", "Milwaukee", or "Milwaukee, WI" does not appear to yield any matches. So it's not very flexible with human input.

**Comment by woodruffw** [comment]
A good stop-gap here would be to take the current Wolfram|Alpha (`!wa`) plugin and use its functionality for weather-only queries. Something like `"weather in {query}"` would probably work just fine.

**Comment by woodruffw** [comment]
https://openweathermap.org/

**Comment by woodruffw** [comment]
#81.
