### ISSUE TITLE
How to login as admin?

### ISSUE THREAD

**Issue by cloneman** [woodruffw/yossarian-bot#77]
I can't figure out how to login as administrator. I see how to set nicks ... but surely there must be a password?

**Comment by rmNULL** [comment]
consider setting your nick under in the config file.
 [Look here for an example](https://github.com/woodruffw/yossarian-bot/blob/master/config.yml.example)

**Comment by woodruffw** [comment]
@rmNULL's suggestion is correct. Also, see https://github.com/woodruffw/yossarian-bot/blob/master/extend/auth.rb for the bot's concept of admin authentication: the nick must be both in the admin list *and* registered/identified on the server.

**Comment by cloneman** [comment]
Oh I see. So that means it won't work a network that doesn't have services, like Efnet?

**Comment by woodruffw** [comment]
> So that means admin won't work a network that doesn't have services, like Efnet?

Yes, probably. Sorry if that makes usage difficult for you. I'm happy to accept patches that allow for different kinds of admin attestation!

**Comment by woodruffw** [comment]
Closing as stale/answered.
